### ISSUE TITLE
Can't get to load on 3.60

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/NRedneck-Vita#1]
Copying REDNECK.grp to ox0:data/NRedneck

Crash on load

Check log file

Log file states "can't find DUKE3D.grp"

Rename it, still won't load.

Assume I also need REDNECK.RTS too? Tried that too.

I have dump files too if needed.

**Comment by Rinnegatamante** [comment]
![immagine](https://user-images.githubusercontent.com/9152710/80986661-298efd80-8e31-11ea-9c8c-599eebf66518.png)
That's the supposed data folder.

**Comment by Sarkie** [comment]
figured it out, the data .zip has two nredneck folders, so when it unzips with vhbb it creates the wrong structure
